Short and long options to the tools

diff --git a/create_vm b/create_vm
--- a/create_vm
+++ b/create_vm
@@ -1,15 +1,8 @@
 #!/bin/bash
 
-usage="Usage: $0 <path> <name virtual machine> <name disk> <ubuntu iso> <user> <password>"
-
 __cleanup()
 {
 	SIGNAL=$1
-
-	echo ""
-	echo "Usage:"
-	echo "  <path>: path that will be used to write the disk and the vm to"
-	echo "  <name virtual machine>: free to choose name for the VM"
 
 	if [ -n "$SIGNAL" ]
 	then
@@ -18,17 +11,98 @@ __cleanup()
 	fi
 }
 
+__message()
+{
+	echo
+	echo "Usage:"
+	echo " $0 <path> <virtual-machine-name> <disk-name> <iso-file> <user> [password]"
+	echo ""
+	echo "Create a virtual machine including disk with installed operating system and user account."
+	echo
+	echo "Options:"
+	echo " -P, --path                   path that will be used to write the disk and the vm to"
+	echo " -v, --virtual-machine-name   free to choose name for the vm"
+	echo " -d, --disk-name              free to choose name for the vm"
+	echo " -i, --iso-file               iso (only tested with ubuntu-20.04.3-desktop-amd64.iso)"
+	echo " -u, --user                   username on vm"
+	echo " -p, --password               password of vm user (if omitted, asked for interactively)"
+	echo
+	echo " -h, --help                   display this help"
+	echo
+	echo "For more details see https://github.com/mrquincle/autorun_github_runner."
+}
+
+trap __message EXIT
+
+# Requires GNU getopt. If long options are required, install it on OS X and FreeBSD.
+OPTS=$(getopt --options P:v:d:i:u:p:h \
+	--long path:,virtual-machine-name:,disk-name:,iso-file:,user:,password:,help \
+	--name "$0" -- "$@")
+
+# If previous command returns non-zero exit code, something went wrong
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTS"
+
+password=
+while true; do
+	case "$1" in
+		-P | --path )
+			path="$2";
+			shift 2
+			;;
+		-v | --virtual-machine-name )
+			vm="$2"
+			shift 2
+			;;
+		-d | --disk-name )
+			disk="$2"
+			shift 2
+			;;
+		-i | --iso-file )
+			iso="$2"
+			shift 2
+			;;
+		-u | --user )
+			user="$2"
+			shift 2
+			;;
+		-p | --password)
+			password="$2"
+			shift 2
+			;;
+		-h | --help)
+			exit 0
+			;;
+		-- )
+			shift
+			;;
+		* )
+			break;
+			;;
+	esac
+done
+
+if [ -z "$path" ] || [ -z "$vm" ] || [ -z "$disk" ] || [ -z "$iso" ] || [ -z "$user" ]; then
+	echo "Not enough arguments"
+	exit
+fi
+
+if [ -z "$password" ]; then
+	echo -n "No password given, enter it now: "
+	read -s password
+fi
+
 trap __cleanup EXIT
 
-path=${1:? "$usage"}
-vm=${2:? "$usage"}
-disk=${3:? "$usage"}
-iso=${4:? "$usage"}
-user=${5:? "$usage"}
-password=${6:? "$usage"}
+if [ -z "$password" ]; then
+	echo
+	echo "Sorry, password required. Exit."
+	exit 2
+fi
 
 # Only tested with
-echo "Only tested with ubuntu-20.04.3-desktop-amd64.iso"
+echo "Note, only tested with ubuntu-20.04.3-desktop-amd64.iso"
 
 # Create a disk of 20 GB
 disk_vdi="$path/$disk/$disk.vdi"
